name: Bestille
version: 1.0.0
main: fr.ziarzer.BestillePlugin
api-version: '1.21'

author: ZiarZer
website: www.github.com/ZiarZer

commands:
  friends:
    usage: /friends
  friendship:
    usage: /friendship <player>
  seefriendship:
    usage: /seefriendship <player> [<player>]
    permission: op
